matrix/matrix/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from neo import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('neo',include('neo.urls')),
    path('logout/', views.user_logout, name='logout'),
]

matrix/neo/urls.py
# each appliction will have its URL file which will be called by the project
from django.urls import path

from neo import views

app_name = 'neo'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_logout/',views.user_login,name='user_login'),
    path('upload/',views.file_upload,name='file_upload'),
    path('dashboard/',views.file_dashboard,name='file_dashboard'),
    path('show_file/<path:file_path>/', views.show_file, name='show_file'),
    path('download_file', views.download_file, name='download_file' )
]

matrix/neo/models.py
from django.db import models

# we will be using django's existing user models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
class FileTransferInfo(models.Model):

    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    sender_name = models.CharField(max_length=255, null=True, blank=True, verbose_name='Sender Name')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    file_path = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.sender.username} to {self.receiver.username}"
    
from storages.backends.gcloud import GoogleCloudStorage
storage = GoogleCloudStorage()
class UploadToBucket():
    @staticmethod
    def upload_files(file, filename):
        try:
            target_path = '/files/' + filename
            path = storage.save(target_path, file)
            return storage.url(path)
        except Exception as e:
            print(e)

matrix/neo/forms.py
from django import forms
from django.contrib.auth.models import User
from neo.models import UserProfileInfo
from django.forms import TextInput, EmailInput




class UserForm(forms.ModelForm):

    password = forms.CharField(widget = forms.PasswordInput(attrs={'placeholder' :'Email', 'style': 'width: 300px;','class': 'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'User Name', 'style': 'width: 300px;','class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder' :'Email', 'style': 'width: 300px;','class': 'form-control'}))


    class Meta():
        model = User
        fields = ('username', 'email', 'password')



# class UserProfileInfo(forms.ModelForm):
#     class Meta():
#         model = UserProfileInfo
#         fields = ('portfolio_site','profile_pic')

matrix/neo/views.py
from django.shortcuts import render


from neo.forms import UserForm
#importing http to send the responses
from django.http import HttpResponse

from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from django.core.files.base import ContentFile


# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

#Importing Models
from .models import UserProfileInfo
from .models import FileTransferInfo
from .models import UploadToBucket
from django.contrib.auth.models import User
from django.core.files.storage import default_storage
from datetime import datetime
from google.cloud import storage
from django.core.files.storage import default_storage
from django.http import FileResponse


from django.core.files.storage import default_storage
# Create your views here.


@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'neo/login.html', {})



def index(request):
    return render(request,'neo/index.html')



def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()


            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'neo/registration.html',
                          {'user_form':user_form,
                           'registered':registered})

#function for file upload
@login_required
def file_upload(request):
    if request.method == 'POST':
        # First get the receiver name and file
        sender_user = request.user

        receiver_email = request.POST.get('reciever_email')

        secret_key = request.POST.get('secret_key')
        
        upload_file = request.FILES['upload_file']

        fs = FileSystemStorage() #defaults to   MEDIA_ROOT  
        file_name = fs.save(upload_file.name, upload_file)

        file_url = fs.url(file_name)

        try:
            # Get the corresponding user with the provided email
            receiver_user = User.objects.get(email=receiver_email)
            
        except User.DoesNotExist:
            # Handle the case where the receiver user does not exist
            return HttpResponse("Receiver does not exist" )
        

        
        try:
            #Uploading file to GCP bucket

            import base64
            import os
            from cryptography.fernet import Fernet
            from cryptography.hazmat.primitives import hashes
            from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
            password = secret_key

            password_res = bytes(password, 'utf-8')

            salt = 'lkjsadl;kfjhawlikercjnfowilcnehkrgjcinouw3ehfcn1kjqnwkefn90123848976592743(*&(*&^*%&^oiusjr0928374598237,ghdomilw3;eujf npqxoi34;luwrcjto js,rhgdkcmxlas'
            res = salt.encode('utf-8')
            kdf = PBKDF2HMAC(
                algorithm=hashes.SHA256(),
                length=32,
                salt= res,
                iterations=480000,
            )
            key = base64.urlsafe_b64encode(kdf.derive(password_res))
            
            fernet = Fernet(key)
            from pathlib import Path
            import os
            # Build paths inside the project like this: BASE_DIR / 'subdir'.
            BASE_DIR = Path(__file__).resolve().parent.parent

            # to let django know where our media dir is
            MEDIA_DIR= os.path.join(BASE_DIR,"media")
            final_path = os.path.join(MEDIA_DIR,file_name)
 
            with open(final_path, 'rb') as file:
                original = file.read()

            encrypted = fernet.encrypt(original)

            with open(final_path, 'wb') as encrypted_file:
                encrypted_file.write(encrypted)

            current_date = datetime.now()
            timestamp = current_date.strftime("%Y%m%d%H%M%S")
            object_path = f"{current_date.year}/{current_date.month}/{current_date.day}/{timestamp}_{upload_file}"
            
            with open(final_path,'r') as f:
                contents = f.read()
            
            byte_data = contents.encode('utf-8')

            # Create a ContentFile from byte data
            content_file = ContentFile(byte_data)
        
            object_uri = UploadToBucket.upload_files(content_file,object_path)
            # return HttpResponse("File Successfully Transferred")
            
        except Exception as e:
            print(e)
            return HttpResponse("Error while uploading file. Please try again after some time")
        
        FileTransferInfo.objects.create(sender=sender_user, sender_name=sender_user, receiver=receiver_user, file_path=object_path)

        success_data = {}
        success_data['file_name'] = upload_file
        success_data['receiver_email'] = receiver_email

        return render(request, 'neo/transfer_success.html', {'data':success_data})

    else:
        #rendering upload form
        return render(request, 'neo/upload.html', {})
    
#function for file dashboard
@login_required
def file_dashboard(request):
    current_user = request.user

    try:
        user_data_entries = FileTransferInfo.objects.filter(receiver=current_user).values()
        #user_data_entries = user_data_entries.filter(receiver=current_user)
        for data_entries in user_data_entries:
            data_entries['file_name'] = data_entries['file_path'].split('/')[-1]
            data_entries['file_name'] = data_entries['file_name'].split('+')[-1]

        return render(request,'neo/dashboard.html',{'user_data_entries': user_data_entries})
    except Exception as e:
        print(e)
        return HttpResponse("Error while loading file. Please try again after some time")

#function to download files
@login_required    
def show_file(request, file_path):
    file = {}
    file['file_path'] = file_path
    file['file_name'] = file_path.split('/')[-1]
    file['file_name'] = file['file_name'].split('+')[-1]
    #Render the download template with the file URL
    return render(request,'neo/download_file.html',{'file': file})

@login_required
def download_file(request):
    file_path = request.POST.get('file_path')
    file_path = f"files/{file_path}"
    file = default_storage.open(file_path)

    with default_storage.open(file_path, 'r') as gcs_file:
        # Get the content of the file
        file_content = gcs_file.read()
    
    file_name = request.POST.get('file_name')
    # print(type(file_name))


    from pathlib import Path
    import os
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent

    # to let django know where our media dir is
    MEDIA_DIR= os.path.join(BASE_DIR,"media")
    final_path = os.path.join(MEDIA_DIR,file_name)

    print(final_path)

    file_result_data = file_content.decode('utf-8')

    with open(final_path, 'w') as django_file:
        # Write the content to the Django file
        django_file.write(file_result_data)
    
    import base64
    import os
    from cryptography.fernet import Fernet
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

    key = request.POST.get('secret_key')

    try:
        password_dec = bytes(key, 'utf-8')

        salt = 'lkjsadl;kfjhawlikercjnfowilcnehkrgjcinouw3ehfcn1kjqnwkefn90123848976592743(*&(*&^*%&^oiusjr0928374598237,ghdomilw3;eujf npqxoi34;luwrcjto js,rhgdkcmxlas'
        res = salt.encode('utf-8')
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt= res,
            iterations=480000,
        )

matrix/templates/neo/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Secure File Transfer App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body class="override">
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Secure File Transfer</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'neo:register' %}">Register</a></li>

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'neo:file_upload' %}">Transfer File</a></li>
            <li><a href="{% url 'neo:file_dashboard' %}">File Dashboard</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'neo:user_login' %}">Login</a></li>
          {% endif %}
          
        </ul>
      </div>
      
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

matrix/templates/neo/dashboard.html
{% extends "neo/base.html" %}
{% load static %}

{% block body_block %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h4>File(s) Available for Download</h4>
        </div>
        <div class="panel-body">
            <div class="alert alert-warning" role="alert">
                Please note files uploaded are deleted after 7 days.
              </div>
            {% if user_data_entries %}
                <table class="table table-bordered table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Sender</th>
                            <th>File Name</th>
                            <th>Download Link</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in user_data_entries %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ entry.sender_name }}</td>
                                <td>{{ entry.file_name }}</td>
                                <td><a class="link-primary" href="{% url 'neo:show_file' entry.file_path %}">Download</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No files available for download.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

matrix/templates/neo/download_file.html
{% extends "neo/base.html" %}
{% load static %}

{% block body_block %}
<div class="container">
    <div>
        <form method="post" enctype="multipart/form-data" action="{% url 'neo:download_file' %}">
            {% csrf_token %}
            {# A more "HTML" way of creating the login form#}
            <div class="col-md-8 col-md-offset-2">
              <div class="panel panel-default">
                  <div class="panel-heading">
                    Download File
                  </div>
                  <div class="alert alert-warning" role="alert">
                      Please note files uploaded are deleted after 7 days.
                    </div>
                  <div class="panel-body">
                      {% if error_message %}
                          <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                      {% endif %}
                      <div class="form-group clearfix">
                          <label for="file_name" name="file_name" class="col-md-4 control-label text-right">File Name:</label>
                          <div class="col-md-6">
                              {{ file.file_name }}
                          </div>
                          <input type="hidden" id="file_path" name="file_path" value="{{ file.file_path }}" />
                          <input type="hidden" id="file_name" name="file_name" value="{{ file.file_name }}" />
                      </div>
                      <div class="form-group clearfix">
                        <label for="secret_key" name="secret_key" class="col-md-4 control-label text-right">Encryption Key:</label>
                        <div class="col-md-6">
                            <input type="text" name="secret_key" placeholder="Key">
                        </div>
                    </div>
                      
                      <div class="col-md-6 col-md-offset-4">
                          <input name="download" type="submit" value="Download" class="btn btn-success" /> &nbsp;
                      </div>
                  </div>
              </div>
          </div>
  
          </form>

    </div>
  </div>

{% endblock %}

matrix/templates/neo/index.html
{% extends "neo/base.html" %}
{% block body_block %}

<div class="container" width="100%" >
  <div class="jumbotron">
    <h2>Secure File Transfer Application</h2>
  </div>
  <div>
    {% if user.is_authenticated %}
        <h3>Welcome {{ user.username }}!</h3>
    {% else %}
        <h3>Welcome to the site!</h3>
    {% endif %}
  </div>
  <div>
    <p style="color:rgb(22, 21, 21);">
      Welcome to a no-trust platform where you can securely transfer a file to the desired recipient securely.
    </p>
  </div>
</div>

{% endblock %}

matrix/templates/neo/login.html
{% extends 'neo/base.html' %}
{% block body_block %}
  <div class="container">
    <div>

        <form method="post" action="{% url 'neo:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                  Login
                </div>
                <div class="panel-body">
                    {% if error_message %}
                        <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                    {% endif %}
                    <div class="form-group clearfix">
                        <label for="username" name="username" class="col-md-4 control-label text-right">Username:</label>
                        <div class="col-md-6">
                            <input type="text" name="username" placeholder="Username">
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label for="password" name="password" class="col-md-4 control-label text-right">Password:</label>
                        <div class="col-md-6">
                            <input name="password" type="password" class="form-control" />
                        </div>
                    </div>
                    <div class="col-md-6 col-md-offset-4">
                        <input name="login" type="submit" value="Login" class="btn btn-success" /> &nbsp;
                        <a href="{% url 'neo:register' %}">or Register</a>
                    </div>
                </div>
            </div>
        </div>

        </form>

    </div>
  </div>
{% endblock %}

matrix/templates/neo/registration.html
{% extends "neo/base.html" %}
{% load static %}

{% block body_block %}
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default">
    {% if registered %}
      <p class="text-success p-d ml-b">Thank you for registering</p>
    {% else %}
    <div class="panel-heading">
      <h3>Register Here</h3>
      <h4>Fill out the below form:</h4>

    </div>

      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="form-group clearfix">
          <div class="panel-body">
            {{ user_form.as_p }}
            <input type="submit" class="btn btn-success" name="" value="Register">
        </div>
      </form>

    {% endif %}

  </div>

</div>

{% endblock %}

matrix/templates/neo/transfer_success.html
{% extends "neo/base.html" %}
{% load static %}

{% block body_block %}
<div class="container" width="100%" >
    <div class="alert alert-warning" role="alert">
        Please note files uploaded are deleted after 7 days.
    </div>
    <div class="jumbotron" style="background-color:#c0d0c0;">
      <h4>You have successfully transferred encrypted file : '{{data.file_name}}' to receipent : '{{data.receiver_email}}' </h4>
      <h5>Please share the encryption key via a secure channel to avoid any unauthorized access.</h5>
    </div>
  </div>

{% endblock %}

matrix/templates/neo/upload.html
{% extends "neo/base.html" %}
{% load static %}

{% block body_block %}
<div class="container">
    <div>

        <form method="post" enctype="multipart/form-data" action="{% url 'neo:file_upload' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                  File Transfer
                </div>
                <div class="alert alert-warning" role="alert">
                    Please note files uploaded are deleted after 7 days.
                  </div>
                <div class="panel-body">
                    {% if error_message %}
                        <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                    {% endif %}
                    <div class="form-group clearfix">
                        <label for="receiver_email" name="receiver_email" class="col-md-4 control-label text-right">Receiver Email:</label>
                        <div class="col-md-6">
                            <input type="text" name="reciever_email" placeholder="Receiver Email">
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label for="secret_key" name="secret_key" class="col-md-4 control-label text-right">Encryption Key:</label>
                        <div class="col-md-6">
                            <input type="text" name="secret_key" placeholder="Key">
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label for="upload_file" name="upload_file" class="col-md-4 control-label text-right">Upload File:</label>
                        <div class="col-md-6">
                            <input type="file" class="form-control-file" id="upload_file" name=upload_file required style=" display: inline !important " />
                        </div>
                        
                    </div>
                    
                    <div class="col-md-6 col-md-offset-4">
                        <input name="upload" type="submit" value="Transfer" class="btn btn-success" /> &nbsp;
                    </div>
                </div>
            </div>
        </div>

        </form>

    </div>
  </div>

{% endblock %}